name: ui_fresh_app
description: This is an application that supports users to order drinks from agents, beverage brands around the world.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  flutter_svg: ^0.23.0+1
  blur: ^3.0.0
  cupertino_icons: ^1.0.2
  simple_gradient_text: ^1.2.2
  dots_indicator: ^2.0.0
  dotted_line: ^3.1.0
  iconsax: ^0.0.8
  another_xlider: ^1.0.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    #images 
    - assets/images/
    - assets/images/common/
    - assets/images/authentication/
    - assets/images/background/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/account/
    - assets/images/accountant/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/sfprotext/SFProText-Ultralight.otf
          style: normal
          weight: 100
        - asset: assets/fonts/sfprotext/SFProText-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/sfprotext/SFProText-Thin.otf
          style: normal
          weight: 200
        - asset: assets/fonts/sfprotext/SFProText-ThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/sfprotext/SFProText-Light.otf
          style: normal
          weight: 300
        - asset: assets/fonts/sfprotext/SFProText-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/sfprotext/SFProText-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/sfprotext/SFProText-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/sfprotext/SFProText-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/sfprotext/SFProText-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/sfprotext/SFProText-Semibold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/sfprotext/SFProText-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/sfprotext/SFProText-Bold.otf
          style: normal
          weight: 700
        - asset: assets/fonts/sfprotext/SFProText-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/sfprotext/SFProText-Heavy.otf
          style: normal
          weight: 800
        - asset: assets/fonts/sfprotext/SFProText-HeavyItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/sfprotext/SFProText-Black.otf
          style: normal
          weight: 900
        - asset: assets/fonts/sfprotext/SFProText-BlackItalic.otf
          style: italic
          weight: 900